In [34]:
# 임포트
import cv2
import matplotlib.pyplot as plt
import os
import random
import numpy as np
import pandas as pd


In [3]:
# 테스트
img = cv2.imread("image/test1.jpg", cv2.IMREAD_GRAYSCALE)

np.set_printoptions(threshold=1000)
print(img)


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [35]:
# 상의 파일 불러오기

input_dir = "./target/top/"
#output_dir = "./image/output/"

#imgarr = np.array([])
imgarr = []

if not os.path.exists(input_dir) :
    os.mkdir(input_dir)

#if not os.path.exists(output_dir) :
#    os.mkdir(output_dir)    

# 이미지 불러오기
file_list = os.listdir(input_dir)

for file in file_list :
    
    img = cv2.imread(input_dir + file,  cv2.IMREAD_GRAYSCALE)
    
    imgarr.append(np.hstack(img))
    
    #imgarr = np.append(imgarr, img, axis = 0)
    


In [ ]:
# 하의 파일 불러오기

input_dir = "./target/bottom/"
#output_dir = "./image/output/"

#imgarr = np.array([])
imgarr2 = []

if not os.path.exists(input_dir) :
    os.mkdir(input_dir)

#if not os.path.exists(output_dir) :
#    os.mkdir(output_dir)    

# 이미지 불러오기
file_list = os.listdir(input_dir)

for file in file_list :
    
    img = cv2.imread(input_dir + file,  cv2.IMREAD_GRAYSCALE)
    
    imgarr2.append(np.hstack(img))
    
    #imgarr = np.append(imgarr, img, axis = 0)
    


In [4]:
imgarr = np.array(imgarr)
imgarr2 = np.array(imgarr2)

In [5]:
data=np.vstack((imgarr,imgarr2))

In [6]:
# X data 완성
img_df = pd.DataFrame(data)
img_df

0      1      2      3      4      5      6      7      8      9      \
0        0      0      0      0      0      0      0      0      0      0   
1        0      0      0      0      0      0      0      0      0      0   
2        0      0      0      0      0      0      0      0      0      0   
3        0      0      0      0      0      0      0      0      0      0   
4        0      0      0      0      0      0      0      0      0      0   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
995      0      0      0      0      0      0      0      0      0      0   
996      0      0      0      0      0      0      0      0      0      0   
997      0      0      0      0      0      0      0      0      0      0   
998      0      0      0      0      0      0      0      0      0      0   
999      0      0      0      0      0      0      0      0      0      0   

     ...  65526  65527  65528  65529  65530  65531  65532  65533  65534  65535  
0    ...      0      0      0      0      0      0      0      0      0      0  
1    ...      0      0      0      0      0      0      0      0      0      0  
2    ...      0      0      0      0      0      0      0      0      0      0  
3    ...      0      0      0      0      0      0      0      0      0      0  
4    ...      0      0      0      0      0      0      0      0      0      0  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
995  ...      0      0      0      0      0      0      0      0      0      0  
996  ...      0      0      0      0      0      0      0      0      0      0  
997  ...      0      0      0      0      0      0      0      0      0      0  
998  ...      0      0      0      0      0      0      0      0      0      0  
999  ...      0      0      0      0      0      0      0      0      0      0  

[1000 rows x 65536 columns]

In [7]:
res = []
for i in range(0,500):
    res.append(1)

In [8]:
for i in range(0,500):
    res.append(0)

In [9]:
# y data 완성
res_df = pd.DataFrame(res)
res_df

0
0    1
1    1
2    1
3    1
4    1
..  ..
995  0
996  0
997  0
998  0
999  0

[1000 rows x 1 columns]

# 여기부터 학습 시작

In [10]:
from xgboost.sklearn import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier # 분류 모델
# 정확도 측정 도구
from sklearn.metrics import accuracy_score


from lightgbm import LGBMClassifier

from lightgbm import early_stopping
from lightgbm import log_evaluation

In [29]:
X_train, X_test, y_train, y_test = train_test_split(img_df, res_df, test_size=0.2)

In [30]:
lgb_img = LGBMClassifier(n_estimators=400)

In [31]:
lgb_img.fit(X_train, y_train, eval_set=[(X_test, y_test)], callbacks=[early_stopping(100), log_evaluation(1)])

C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:99: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
C:\ProgramData\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


[1]	valid_0's binary_logloss: 0.650343
Training until validation scores don't improve for 100 rounds
[2]	valid_0's binary_logloss: 0.602791
[3]	valid_0's binary_logloss: 0.565982
[4]	valid_0's binary_logloss: 0.533069
[5]	valid_0's binary_logloss: 0.500725
[6]	valid_0's binary_logloss: 0.469803
[7]	valid_0's binary_logloss: 0.453298
[8]	valid_0's binary_logloss: 0.435177
[9]	valid_0's binary_logloss: 0.415238
[10]	valid_0's binary_logloss: 0.397445
[11]	valid_0's binary_logloss: 0.385187
[12]	valid_0's binary_logloss: 0.371404
[13]	valid_0's binary_logloss: 0.361702
[14]	valid_0's binary_logloss: 0.346051
[15]	valid_0's binary_logloss: 0.336347
[16]	valid_0's binary_logloss: 0.320129
[17]	valid_0's binary_logloss: 0.3107
[18]	valid_0's binary_logloss: 0.302422
[19]	valid_0's binary_logloss: 0.296101
[20]	valid_0's binary_logloss: 0.288539
[21]	valid_0's binary_logloss: 0.283374
[22]	valid_0's binary_logloss: 0.275791
[23]	valid_0's binary_logloss: 0.271537
[24]	valid_0's binary_logloss

LGBMClassifier(n_estimators=400)

In [32]:
pre = lgb_img.predict(X_test)
accuracy_score(pre, y_test)

0.93

In [23]:
import joblib

In [33]:
joblib.dump(lgb_img, './model.pkl')

['./model.pkl']